### ISSUE TITLE
About the time info in org-html-postamble

### ISSUE THREAD

**Issue by heypnus** [CodeFalling/hexo-renderer-org#10]
I updated my blog today (2016-02-10) and restart the server, then it said the following words in the footer:

> Last Updated <2015-11-29 Sun 13:08>.
> Render by hexo-renderer-org with Emacs 24.5.1 (Org mode 8.2.10)

However, the attribute _Last Updated_ is now referring to **creation time**. I think it's better to be modified as <2016-02-10 Wed 00:15>  ;-)

Thank you.

**Comment by CodeFalling** [comment]
My mistake, maybe change
```yaml
org:
  emacs: '/Applications/Emacs.app/Contents/MacOS/Emacs'
  common: |
          #+OPTIONS: toc:nil
          #+BIND: org-html-postamble \"Last Updated %d.</br>Render by <a href='https://github.com/CodeFalling/hexo-renderer-org'>hexo-renderer-org</a> with %c\"
  cachedir: './hexo-org-cache/'
```

into 

```yaml
org:
  emacs: '/Applications/Emacs.app/Contents/MacOS/Emacs'
  common: |
          #+OPTIONS: toc:nil
          #+BIND: org-html-postamble \"Last Updated %C.</br>Render by <a href='https://github.com/CodeFalling/hexo-renderer-org'>hexo-renderer-org</a> with %c\"
  cachedir: './hexo-org-cache/'

```

will works?
