### ISSUE TITLE
Convert error in the inline emphasis

### ISSUE THREAD

**Issue by zou-mono** [CodeFalling/hexo-renderer-org#21]
你好，
      最近我发现在使用inline emphasis时，例如=...=， ~...~，无法正常转换为<code><\code>。经过测试，只有当诸如"或者.这样的符号开头时会发生这种错误，例如~.bash~，="hello"=。我知道可以通过设置org-emphasis-regexp-components来解决这种问题，但是这种设置只能保证使用org-mode自己的export-to-html生成html时不会有问题，但是如果使用这个插件生成的html还是会出问题，请问有办法解决吗？谢谢！

**Comment by zou-mono** [comment]
我暂时找到了一个不是很优雅的解决方法，就是插入一个零宽字符，见http://stackoverflow.com/questions/28331541/orgmode-inlining-verbatim-material

**Comment by frapples** [comment]
你提到说设置org-emphasis-regexp-components就能解决问题。其实org-mode可以使用#+BIND 语法来设置elisp变量的值。而这个插件提供了common配置项来在org文件前面加一些东西。

比如我的设置可能就是这样的：
```
org:
  emacs: 'emacs'
  common: |
          #+OPTIONS: toc:nil
          #+OPTIONS: ^:nil
          #+BIND: org-html-postamble \"\"
```

注意我在这里把elisp变量org-html-postamble设置为了空字符串。
